## Import Library

In [119]:
!python --version

Python 3.7.1

In [120]:
import pandas as pd
import numpy as np
import time

In [121]:
import random
random.seed(0)

In [122]:
df = pd.read_excel('Data Stroke Asli.xlsx', engine='openpyxl')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df = df.drop('No', axis=1)
df

,Tekanan Darah,Diabetes,Riwayat Keluarga,Merokok,Kolesterol,Aktifitas Fisik,Diet,Riwayat Fabrilasi Atrium,Tingkat Potensi
0,Rendah,120,Iya,Tidak,183,Rutin Olahraga,20.57,Beraturan,Risiko Tinggi
1,Rendah,180,Iya,Tidak,100,Rutin Olahraga,20.30,Beraturan,Risiko Tinggi
2,Tinggi,230,-,Merokok,251,Kadang Olahraga,32.44,Tidak Beraturan,Risiko Tinggi
3,Tinggi,210,-,Merokok,241,Tidak Pernah Olahraga,32.18,-,Risiko Tinggi
4,Tinggi,250,-,Merokok,249,Kadang Olahraga,26.35,-,Risiko Tinggi
...,...,...,...,...,...,...,...,...,...
145,Rendah,90,Tidak Ada,Tidak,210,Tidak Pernah Olahraga,22.00,Beraturan,Risiko Rendah
146,Rendah,100,Tidak Ada,Tidak,108,Rutin Olahraga,20.00,-,Risiko Rendah
147,Rendah,143,Tidak Ada,Tidak,195,Rutin Olahraga,18.93,Beraturan,Risiko Rendah
148,Sedang,180,-,Merokok,220,Tidak Pernah Olahraga,25.70,Tidak Beraturan,Risiko Tinggi
149,Tinggi,178,-,Kadang,120,Tidak Pernah Olahraga,20.00,Tidak Beraturan,Risiko Tinggi

## Jumlah Kelas

In [123]:
print('Jumlah data risiko tingkat rendah:', df[(df['Tingkat Potensi'] == 'Risiko Rendah')]['Tingkat Potensi'].count())
print('Jumlah data risiko tingkat tinggi:', df[(df['Tingkat Potensi'] == 'Risiko Tinggi')]['Tingkat Potensi'].count())

Jumlah data risiko tingkat rendah: 86
Jumlah data risiko tingkat tinggi: 64

## Jumlah Missing Value

In [124]:
m = df.shape[1]
n = df.shape[0]

In [125]:
print(n, m)

150 9

In [126]:
print("Jumlah Data Hilang Atribut Riwayat Keluarga: ",
      df[(df['Riwayat Keluarga'] == '-')]['Riwayat Keluarga'].count())
print("Jumlah Data Hilang Atribut Riwayat Fabrilasi Atrium: ",
      df[(df['Riwayat Fabrilasi Atrium'] == '-')]['Riwayat Fabrilasi Atrium'].count())

Jumlah Data Hilang Atribut Riwayat Keluarga:  97
Jumlah Data Hilang Atribut Riwayat Fabrilasi Atrium:  51

In [127]:
print("Jumlah Nilai Tidak Ada Pada Atribut Riwayat Keluarga: ",
      df[(df['Riwayat Keluarga'] == 'Tidak Ada')]['Riwayat Keluarga'].count())
print("Jumlah Nilai Ada Atribut Riwayat Keluarga: ",
      df[(df['Riwayat Keluarga'] == 'Iya')]['Riwayat Keluarga'].count())
print('\n')
print("Jumlah Nilai Beraturan Pada Atribut Riwayat Fabrilasi Atrium: ",
      df[(df['Riwayat Fabrilasi Atrium'] == 'Beraturan')]['Riwayat Fabrilasi Atrium'].count())
print("Jumlah Nilai Tidak Beraturan Pada Atribut Riwayat Fabrilasi Atrium: ",
      df[(df['Riwayat Fabrilasi Atrium'] == 'Tidak Beraturan')]['Riwayat Fabrilasi Atrium'].count())

Jumlah Nilai Tidak Ada Pada Atribut Riwayat Keluarga:  51
Jumlah Nilai Ada Atribut Riwayat Keluarga:  2


Jumlah Nilai Beraturan Pada Atribut Riwayat Fabrilasi Atrium:  78
Jumlah Nilai Tidak Beraturan Pada Atribut Riwayat Fabrilasi Atrium:  21

## Imputasi

In [128]:
df['Riwayat Keluarga'] = df['Riwayat Keluarga'].replace('-', 'Tidak Ada')
df['Riwayat Fabrilasi Atrium'] = df['Riwayat Fabrilasi Atrium'].replace('-', 'Beraturan')

In [129]:
df

,Tekanan Darah,Diabetes,Riwayat Keluarga,Merokok,Kolesterol,Aktifitas Fisik,Diet,Riwayat Fabrilasi Atrium,Tingkat Potensi
0,Rendah,120,Iya,Tidak,183,Rutin Olahraga,20.57,Beraturan,Risiko Tinggi
1,Rendah,180,Iya,Tidak,100,Rutin Olahraga,20.30,Beraturan,Risiko Tinggi
2,Tinggi,230,Tidak Ada,Merokok,251,Kadang Olahraga,32.44,Tidak Beraturan,Risiko Tinggi
3,Tinggi,210,Tidak Ada,Merokok,241,Tidak Pernah Olahraga,32.18,Beraturan,Risiko Tinggi
4,Tinggi,250,Tidak Ada,Merokok,249,Kadang Olahraga,26.35,Beraturan,Risiko Tinggi
...,...,...,...,...,...,...,...,...,...
145,Rendah,90,Tidak Ada,Tidak,210,Tidak Pernah Olahraga,22.00,Beraturan,Risiko Rendah
146,Rendah,100,Tidak Ada,Tidak,108,Rutin Olahraga,20.00,Beraturan,Risiko Rendah
147,Rendah,143,Tidak Ada,Tidak,195,Rutin Olahraga,18.93,Beraturan,Risiko Rendah
148,Sedang,180,Tidak Ada,Merokok,220,Tidak Pernah Olahraga,25.70,Tidak Beraturan,Risiko Tinggi
149,Tinggi,178,Tidak Ada,Kadang,120,Tidak Pernah Olahraga,20.00,Tidak Beraturan,Risiko Tinggi

## Pengkodean

In [130]:
df['Tekanan Darah'] = df['Tekanan Darah'].replace(['Rendah', 'Sedang', 'Tinggi'], [0, 1, 2])
df['Riwayat Keluarga'] = df['Riwayat Keluarga'].replace(['Tidak Ada', 'Iya'], [0, 1])
df['Merokok'] = df['Merokok'].replace(['Tidak', 'Kadang', 'Merokok'], [0, 1, 2])
df['Aktifitas Fisik'] = df['Aktifitas Fisik'].replace(['Tidak Pernah Olahraga', 'Kadang Olahraga', 'Rutin Olahraga'], [0, 1, 2])
df['Riwayat Fabrilasi Atrium'] = df['Riwayat Fabrilasi Atrium'].replace(['Tidak Beraturan', 'Beraturan'], [0, 1])
df['Tingkat Potensi'] = df['Tingkat Potensi'].replace(['Risiko Rendah', 'Risiko Tinggi'], [-1, 1])

In [131]:
df

,Tekanan Darah,Diabetes,Riwayat Keluarga,Merokok,Kolesterol,Aktifitas Fisik,Diet,Riwayat Fabrilasi Atrium,Tingkat Potensi
0,0,120,1,0,183,2,20.57,1,1
1,0,180,1,0,100,2,20.30,1,1
2,2,230,0,2,251,1,32.44,0,1
3,2,210,0,2,241,0,32.18,1,1
4,2,250,0,2,249,1,26.35,1,1
...,...,...,...,...,...,...,...,...,...
145,0,90,0,0,210,0,22.00,1,-1
146,0,100,0,0,108,2,20.00,1,-1
147,0,143,0,0,195,2,18.93,1,-1
148,1,180,0,2,220,0,25.70,0,1
149,2,178,0,1,120,0,20.00,0,1

## Ukuran Data latih & Data Uji

In [132]:
n_test = 30
n_train = n - n_test
n_train

120

## Pembagian data uji dan data latih

In [133]:
train = df.iloc[:-n_test,:]
test = df.iloc[-n_test:,:]
print(train.shape[0], test.shape[0])

120 30

In [134]:
train

,Tekanan Darah,Diabetes,Riwayat Keluarga,Merokok,Kolesterol,Aktifitas Fisik,Diet,Riwayat Fabrilasi Atrium,Tingkat Potensi
0,0,120,1,0,183,2,20.57,1,1
1,0,180,1,0,100,2,20.30,1,1
2,2,230,0,2,251,1,32.44,0,1
3,2,210,0,2,241,0,32.18,1,1
4,2,250,0,2,249,1,26.35,1,1
...,...,...,...,...,...,...,...,...,...
115,0,142,0,1,180,2,21.76,1,-1
116,1,186,0,0,193,2,18.86,1,-1
117,0,193,0,0,192,2,17.22,1,-1
118,1,123,0,0,190,2,15.57,1,-1
119,0,80,0,0,238,2,22.00,1,-1

In [135]:
test

,Tekanan Darah,Diabetes,Riwayat Keluarga,Merokok,Kolesterol,Aktifitas Fisik,Diet,Riwayat Fabrilasi Atrium,Tingkat Potensi
120,2,220,0,2,243,0,33.20,0,1
121,2,250,0,2,300,0,32.70,0,1
122,2,180,0,1,274,1,37.05,1,1
123,1,190,0,1,275,1,31.25,1,1
124,0,210,0,0,145,0,32.70,1,-1
125,1,190,0,1,218,2,30.10,1,-1
126,1,250,0,1,259,1,33.24,1,1
127,1,170,0,1,220,1,32.20,0,1
128,0,109,0,0,109,2,23.70,0,-1
129,1,124,0,1,213,1,25.43,1,-1
130,2,232,0,1,247,1,30.49,1,1
131,0,165,0,1,287,1,31.24,1,-1
132,2,231,0,1,204,1,33.35,1,1
133,1,180,0,1,330,0,24.70,1,1
134,0,190,0,1,216,0,30.10,1,-1
135,2,100,0,1,140,0,25.20,1,-1
136,2,240,0,1,248,1,33.40,1,1
137,2,280,0,2,210,1,27.90,1,1
138,1,120,0,1,120,1,23.10,1,-1
139,2,335,0,2,196,0,31.40,0,1
140,1,180,0,1,220,1,33.50,1,-1
141,0,130,0,0,300,2,20.40,1,-1
142,0,192,0,1,238,1,26.90,1,-1
143,0,135,0,0,138,0,23.10,1,-1
144,0,120,0,0,136,1,24.20,1,-1
145,0,90,0,0,210,0,22.00,1,-1
146,0,100,0,0,108,2,20.00,1,-1
147,0,143,0,0,195,2,18.93,1,-1
148,1,180,0,2,220,0,25.70,0,1
149,2,178,0,1,120,0,20.00,0,1

In [136]:
y_train = train['Tingkat Potensi']
y_test = test['Tingkat Potensi']

X_train = train.drop(['Tingkat Potensi'], axis=1)
X_test = test.drop(['Tingkat Potensi'], axis=1)

In [137]:
X_train = pd.DataFrame.to_numpy(X_train).astype(float)
y_train = pd.DataFrame.to_numpy(y_train)

X_test = pd.DataFrame.to_numpy(X_test).astype(float)
y_test = pd.DataFrame.to_numpy(y_test)

## Cross Validation

### SVM-SMO

In [138]:
class Support_Vector_Machine:
    def __init__(self, C, gamma, tol = 0.001,  eps = 1e-05, verbose=False):
        self.C = C
        self.gamma = gamma
        self.tol = tol
        self.eps = eps
        self.iteration = 1
        self.verbose = verbose
    
    def latih(self, X, y):
        self.X = X
        self.y = y
        self.m = X.shape[0]
        self.n = X.shape[1]

        self.alpha, self.b = self.inisialisasi_alpha_b()       
        self.error_cache = self.inisialisasi_error_cache(self.X, self.y)
        
        cek_semua = 1
        jumlah_berubah = 0        
        
        while (jumlah_berubah > 0) or (cek_semua):            
            jumlah_berubah = 0
            if cek_semua:
                self.verbose and print('\nPeriksa Semua')
                for j in range(self.alpha.shape[0]):
                    self.verbose and print(f'\nj: {j}')
                    self.verbose and print('Iterasi ke: ', self.iteration)
                    hasil_opt = self.periksa_sampel(j)
                    jumlah_berubah = jumlah_berubah + hasil_opt
            
            else:
                for j in np.where((self.alpha != 0) & (self.alpha != self.C))[0]:                    
                    self.verbose and print(f'\nj: {j}')
                    self.verbose and print('\nIterasi ke: ', self.iteration)
                    hasil_opt = self.periksa_sampel(j)
                    jumlah_berubah = jumlah_berubah + hasil_opt
            
            if cek_semua == 1:
                cek_semua = 0
            elif jumlah_berubah == 0:
                cek_semua = 1
        self.verbose and print(f'alpha {self.alpha}')
        self.verbose and print(f'b {self.b}')
        print(f'total iterartion {self.iteration}')
                
    def periksa_sampel(self, j):
        yj = self.y[j]
        aj = self.alpha[j]
        ej = self.error_cache[j]

        if (((ej * yj) < -self.tol and aj < self.C) or ((ej * yj) > self.tol and aj > 0)):
            self.verbose and print(f'\n\tj: {j} MELANGGAR KKT')
            if len(self.alpha[(self.alpha != 0) & (self.alpha != self.C)]) > 1:
                if self.error_cache[j] > 0:
                    i = np.argmin(self.error_cache)
                    self.verbose and print(f'\n\tHEU-2 = MIN: {self.error_cache[i]}')
                else:
                    i = np.argmax(self.error_cache)
                    self.verbose and print(f'\n\tHEU-2 = MAX: {self.error_cache[i]}')
                hasil_opt = self.optimisasi(i, j)
                self.iteration += 1
                if hasil_opt:
                    return 1
        
            for i in np.roll(np.where((self.alpha != 0) & (self.alpha != self.C))[0], 
                             np.random.choice(np.arange(self.m))):
                self.verbose and print(f'\n\tHEU-2 = ROLL SV: {i}')
                hasil_opt = self.optimisasi(i, j)
                self.iteration += 1
                if hasil_opt:
                    return 1
        
            for i in np.roll(np.arange(self.m), np.random.choice(np.arange(self.m))):
                self.verbose and print(f'\n\tHEU-2 = ROLL ALL: {i}')
                hasil_opt = self.optimisasi(i, j)
                self.iteration += 1
                if hasil_opt:
                    return 1
        self.verbose and print(f'\n\tj: {j} MEMENUHI KKT')
        self.iteration += 1
        return 0
    
    def optimisasi(self, i, j):
        self.verbose and print(f'\nITERASI KE: {self.iteration}')
        self.verbose and print(f'\n\tTERPILIH: i: {i}, j: {j}')
        if i == j:
            self.verbose and print('\t\tGAGAL! i == j')
            return 0
        
        ai = self.alpha[i]
        aj = self.alpha[j]
        yi = self.y[i]
        yj = self.y[j]
        ei = self.error_cache[i]
        ej = self.error_cache[j]
        self.verbose and print(f'\t\tXi: {self.X[i]}')
        self.verbose and print(f'\t\tXj: {self.X[j]}')
        self.verbose and print(f'\t\tai OLD: {ai}')
        self.verbose and print(f'\t\taj OLD: {aj}')
        self.verbose and print(f'\t\tyi: {yi}')
        self.verbose and print(f'\t\tyj: {yj}')
        self.verbose and print(f'\t\tei: {ei}')
        self.verbose and print(f'\t\tej: {ej}')
        self.verbose and print(f'\t\tfxi: {ei + yi}')
        self.verbose and print(f'\t\tfxj: {ej + yj}')
        
        L, H = self.hitung_L_dan_H(yi, yj, ai, aj, self.C)
        self.verbose and print(f'\t\tL: {L} H: {H}')
        if L == H:
            self.verbose and print('\t\tGAGAL! L == H')
            return 0
        kii, kjj, kij, eta = self.hitung_eta(self.X[i], self.X[j])
        self.verbose and print(f'\n\t\tkii: {kii}, kjj: {kjj}, kij: {kij}, \neta: {eta}')
        aj_baru = self.hitung_aj_baru(aj, yj, ei, ej, eta)
        self.verbose and print(f'aj_baru: {aj_baru}')
        aj_baru = self.pangkas_aj_baru(aj_baru, L, H)
        self.verbose and print(f'aj_baru_pangkas: {aj_baru}')
                
        if np.abs(aj_baru - aj) < (self.eps * (aj_baru + aj + self.eps)):
            self.verbose and print('\n\t\tGAGAL! EPSILON!')
            return 0
        
        ai_baru = self.hitung_ai_baru(ai, aj, aj_baru, yi, yj)
        self.verbose and print(f'\n\t\tai_barunew: {ai_baru}')
        b1, b2 = self.hitung_b1_b2(ai, ai_baru, aj, aj_baru, yi, yj, ei, ej, kii, kjj, kij, self.b)        
        self.verbose and print(f'\n\t\tb1: {b1}, b2: {b2}')
        b_baru = self.hitung_b_baru(ai_baru, aj_baru, b1, b2, self.C)
        self.verbose and print(f'\t\tbnew: {b_baru}')
        self.alpha[i] = ai_baru
        self.alpha[j] = aj_baru
        
        self.hitung_error_cache(i, j, ai, ai_baru, aj, aj_baru, yi, yj, b_baru)
        self.b = b_baru
        self.verbose and print(f'\n\t\terror after ei:{self.error_cache[i]}, ej:{self.error_cache[j]}')
        self.verbose and print('\nERROR CACHE BARU:', i, ':', self.error_cache[i],
             ',', j, self.error_cache[j], 'last:', self.error_cache[-1])
        self.verbose and print(f'\n\tSUCCESS: i: {i}, j: {j}')
        return 1
    
    def inisialisasi_alpha_b(self):        
        alpha = np.zeros(self.m)
        b = 0.0
        return alpha, b
    
    def inisialisasi_error_cache(self, X, y):
        error_cache = self.fungsi_keputusan(X) - y
        return error_cache
    
    def hitung_L_dan_H(self, yi, yj, ai, aj, C):
        if (yi == yj):
            L = max(0, ai + aj - C)
            H = min(C, ai + aj)
        else:
            L = max(0, aj - ai)
            H = min(C, C + aj - ai)
        return L, H
    
    def hitung_eta(self, xi, xj):
        kii = self.hitung_kernel(xi, xi)
        kjj = self.hitung_kernel(xj, xj)
        kij = self.hitung_kernel(xi, xj)
        eta = 2 * kij - kii - kjj
        return kii, kjj, kij, eta
    
    def hitung_aj_baru(self, aj, yj, ei, ej, eta):
        aj_baru = aj - ((yj * (ei - ej)) / eta)
        return aj_baru
    
    def pangkas_aj_baru(self, aj_baru, L, H):
        if aj_baru <= L:
            aj_baru = L
        elif aj_baru >= H:
            aj_baru = H
        return aj_baru
    
    def hitung_ai_baru(self, ai, aj, aj_baru, yi, yj):
        ai_baru = ai + (yi * yj * (aj - aj_baru))
        return ai_baru
        
    def hitung_b1_b2(self, ai, ai_baru, aj, aj_baru, yi, yj, ei, ej, kii, kjj, kij, b):
        b1 = ei + (yi * (ai_baru - ai) * kii) + (yj * (aj_baru - aj) * kij) + b
        b2 = ej + (yi * (ai_baru - ai) * kij) + (yj * (aj_baru - aj) * kjj) + b
        return b1, b2
    
    def hitung_b_baru(self, ai_baru, aj_baru, b1, b2, C):
        if ai_baru > 0 and ai_baru < self.C:
            b_baru = b1
        elif aj_baru > 0 and aj_baru < self.C:
            b_baru = b2
        else:
            b_baru = 0.5 * (b1 + b2)            
        return b_baru    
    
    def hitung_error_cache(self, i, j, ai, ai_baru, aj, aj_baru, yi, yj, b_baru):
        for index, alph in zip([i, j], [ai_baru, aj_baru]):
            if 0.0 < alph < self.C:
                self.error_cache[index] = 0
        non_opt = [n for n in range(self.m) if (n != i and n!= j)]
        self.error_cache[non_opt] += \
            (yi * (ai_baru - ai) * self.hitung_kernel(self.X[i], self.X[non_opt])) + \
            (yj * (aj_baru - aj) * self.hitung_kernel(self.X[j],self.X[non_opt])) + \
            self.b - b_baru
    
    def fungsi_keputusan(self, X_test):
        hasil_fungsi_keputusan = (self.alpha * self.y) @ self.hitung_kernel(self.X, X_test) - self.b
        return hasil_fungsi_keputusan
        
    def hitung_kernel(self, x, y):
        if np.ndim(x) == 1 and np.ndim(y) == 1:
            return np.exp(- self.gamma * (np.linalg.norm(x - y, 2)) ** 2)
        elif (np.ndim(x) == 1 and np.ndim(y) > 1) or (np.ndim(x) > 1 and np.ndim(y) == 1):
            return np.exp(- self.gamma * (np.linalg.norm(x - y, 2, axis = 1)) ** 2)
        else:
            return np.exp(- self.gamma * (np.linalg.norm(x[:, np.newaxis] - y[np.newaxis, :], 2, axis = 2)) ** 2)
    
    def prediksi(self, X):
        hasil_fungsi_keputusan = self.fungsi_keputusan(X)
#         print(hasil_fungsi_keputusan)
        hasil_prediksi = np.where(hasil_fungsi_keputusan < 0, -1, 1)
        return hasil_prediksi
    
    @staticmethod
    def metrics_calc(y, y_pred):
        accuracy = np.round((np.sum(y == y_pred) / y.shape[0]) * 100, 2)
        return accuracy
    
    def __del__(self):
        print('')

In [139]:
np.random.seed(0)
svm = Support_Vector_Machine(C = 10, gamma=0.0005, verbose=False)
# start = time.time()        
svm.latih(X_train, y_train)
# end = time.time()

y_train_pred = svm.prediksi(X_train)
y_test_pred = svm.prediksi(X_test)
print(y_test)
print(y_test_pred)
train_acc = Support_Vector_Machine.metrics_calc(y_train, y_train_pred)
test_acc = Support_Vector_Machine.metrics_calc(y_test, y_test_pred)

# print('Time: ', ((end-start) // 60), 'min', ((end-start) % 60), 'sec')
print('Train accuracy with C: {} gamma: {} is {}'.format(10, 0.0005, train_acc))
print('Test accuracy with C: {} gamma: {} is {}'.format(10, 0.0005, test_acc))

total iterartion 14574
[ 1  1  1  1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1 -1 -1
 -1 -1 -1 -1  1  1]
[ 1  1  1  1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1  1  1 -1  1 -1 -1 -1 -1
 -1  1 -1 -1 -1 -1]
Train accuracy with C: 10 gamma: 0.0005 is 95.0
Test accuracy with C: 10 gamma: 0.0005 is 83.33

In [140]:
X_test[-1]

array([  2., 178.,   0.,   1., 120.,   0.,  20.,   0.])

In [172]:
pasien = svm.prediksi([1, 350, 0, 1, 120, 0, 20, 0])

In [174]:
print(pasien)

1